services:
  postgres:
    image: postgres:17-alpine
    container_name: mint-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mint:
    build:
      context: ./apps/mint
      dockerfile: Dockerfile
    container_name: mint-backend
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/mint:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-True}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,mint}
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432

  frontend:
    build:
      context: ./apps/static-src
      dockerfile: Dockerfile
    container_name: mint-frontend
    command: pnpm dev --host
    volumes:
      - ./apps/static-src:/app
      - ./apps/mint:/mint:ro
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development

volumes:
  postgres_data:
