# Generated by Django 5.2.7 on 2025-10-15 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("minty_mogul", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceitem",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(fields=["name"], name="minty_mogul_name_7998a5_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(fields=["price"], name="minty_mogul_price_d40ed9_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(
                fields=["created_at"], name="minty_mogul_created_ca6303_idx"
            ),
        ),
    ]
