# Generated by Django 5.2.7 on 2025-10-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_continent_map_mapleclass_mob_mobspawn_npc_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="craftingrecipe",
            options={"ordering": ["result_item__name"]},
        ),
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="description",
        ),
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="name",
        ),
        migrations.RemoveField(
            model_name="craftingrecipe",
            name="source_id",
        ),
        migrations.AddIndex(
            model_name="craftingrecipe",
            index=models.Index(
                fields=["result_item", "crafter_npc"],
                name="api_craftin_result__e527f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="craftingrecipe",
            index=models.Index(
                fields=["meso_cost"], name="api_craftin_meso_co_e980e1_idx"
            ),
        ),
    ]
