# Generated by Django 5.2.7 on 2025-10-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_craftingrecipe_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="continent",
            index=models.Index(fields=["name"], name="api_contine_name_0daac9_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["name"], name="api_item_name_733099_idx"),
        ),
        migrations.AddIndex(
            model_name="itemdrop",
            index=models.Index(
                fields=["drop_rate"], name="api_itemdro_drop_ra_90dbb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["name"], name="api_job_name_9706f7_idx"),
        ),
        migrations.AddIndex(
            model_name="map",
            index=models.Index(fields=["name"], name="api_map_name_860b79_idx"),
        ),
        migrations.AddIndex(
            model_name="mapleclass",
            index=models.Index(fields=["name"], name="api_maplecl_name_a256b6_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(fields=["name"], name="api_marketp_name_bc9d12_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(fields=["price"], name="api_marketp_price_8764db_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceitem",
            index=models.Index(
                fields=["created_at"], name="api_marketp_created_f212e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mob",
            index=models.Index(fields=["name"], name="api_mob_name_daa52b_idx"),
        ),
        migrations.AddIndex(
            model_name="mob",
            index=models.Index(fields=["hp"], name="api_mob_hp_72c2bd_idx"),
        ),
        migrations.AddIndex(
            model_name="mob",
            index=models.Index(fields=["exp"], name="api_mob_exp_7ed003_idx"),
        ),
        migrations.AddIndex(
            model_name="npc",
            index=models.Index(fields=["name"], name="api_npc_name_ead8b6_idx"),
        ),
        migrations.AddIndex(
            model_name="npcshopitem",
            index=models.Index(fields=["price"], name="game_npc_sh_price_261119_idx"),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(fields=["name"], name="api_quest_name_bf3a20_idx"),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(
                fields=["quest_line"], name="api_quest_quest_l_5e176d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(
                fields=["required_level"], name="api_quest_require_cf02c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["name"], name="api_region_name_345ac4_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="api_skill_name_fc0d87_idx"),
        ),
    ]
